Models/Cliente.cs
namespace inicio_Mvc_Csharp.Models;

public class Cliente
{
    public int Id { get; set; }
    public string Nombre { get; set; }
    public string Cedula { get; set; }
    public int Edad { get; set; }
    
    
    //Relacion con el producto:
    public int ProductoId { get; set; }     // FK
    public Producto? Producto { get; set; }     // Prop. de nav. opcional
    
}

Models/ErrorViewModel.cs
namespace inicio_Mvc_Csharp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Producto.cs
namespace inicio_Mvc_Csharp.Models;

public class Producto
{
    public int ID { get; set; }
    public string Nombre { get; set; } = string.Empty;  // si ni hay datos, estará vacio.
    public string Descripcion { get; set; } = string.Empty;
    public double Precio { get; set; } 
}

Controllers/ClienteController.cs
using inicio_Mvc_Csharp.Models;
using Microsoft.AspNetCore.Mvc;

namespace inicio_Mvc_Csharp.Controllers;

public class ClienteController : Controller
{
    // Lista para almacenar a todos los clientes:
    private static List<Cliente> _clientes = new List<Cliente>
    {
        new Cliente{Id = 1, Nombre = "Karl", Cedula = "1085310888", Edad = 26, ProductoId = 1},
        new Cliente{Id = 2, Nombre = "Susana", Cedula = "663609213", Edad = 19, ProductoId = 3},
        new Cliente {Id = 3, Nombre = "María", Cedula = "1063352947", Edad = 30, ProductoId = 2}
    };
    
    // Para simular un ID auto_incrementable:
    private int contador = _clientes.Count();
    
    // Index con la lista de productos:

    
    
    // Traigo la lista:
    public IActionResult Index()
    {
        ViewBag.Productos = ProductoController._productos;
        return View(_clientes);
    }
    
    // Para mostrar los detalles de los productos:
    public IActionResult Detalles(int id)
    {
        var clientes_x = _clientes;

        var cli = clientes_x.FirstOrDefault(clientes_x => clientes_x.Id == id);
        if (cli == null)
            return NotFound();
        return View(cli);
    }
    
    
    
    // CREATE:
    public IActionResult Store(Cliente cliente)
    {
        contador++;
        cliente.Id = contador;
        
        cliente.Producto = ProductoController._productos.FirstOrDefault(p => p.ID == cliente.ProductoId);

        
        _clientes.Add(cliente);
        return RedirectToAction("Index");
    }


    // DELETE:
    public IActionResult DeleteCliente(int id_cliente)
    {
        var pro = _clientes.FirstOrDefault(produc => produc.Id == id_cliente);
        if (pro != null)
        {
            _clientes.Remove(pro);
        }
        
        return RedirectToAction("Index");
    }
    

    // EDITAR:  
    // GET: Cliente/Edit/1
    public IActionResult EditCliente(int id)
    {
        var cliente = _clientes.FirstOrDefault(c => c.Id == id);
        if (cliente == null)
        {
            return NotFound();
        }
        return View(cliente);
    }

    [HttpPost]
    public IActionResult EditPost(Cliente cliente)
    {
        var existingCliente = _clientes.FirstOrDefault(c => c.Id == cliente.Id);
        if (existingCliente == null)
        {
            return NotFound();
        }

        // Actualizar propiedades
        existingCliente.Nombre = cliente.Nombre;
        existingCliente.Cedula = cliente.Cedula;
        existingCliente.Edad = cliente.Edad;

        return RedirectToAction("Index");
    }
    
    
    
}

Controllers/HelloController.cs
using Microsoft.AspNetCore.Mvc;

namespace inicio_Mvc_Csharp.Controllers;

public class HelloController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using inicio_Mvc_Csharp.Models;

namespace inicio_Mvc_Csharp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProductoController.cs
using inicio_Mvc_Csharp.Models;
using Microsoft.AspNetCore.Mvc;

namespace inicio_Mvc_Csharp.Controllers;

public class ProductoController : Controller
{

    // Creo una lista de productos (quemada):
    public static List<Producto> _productos = new List<Producto>
    {
        new Producto { ID = 1, Nombre = "Televisor", Precio = 5020232, Descripcion = "Es muy bueno" },
        new Producto { ID = 2, Nombre = "Pc gamer", Precio = 67564343, Descripcion = "Regular" },
        new Producto { ID = 3, Nombre = "Eq. sonido", Precio = 2000, Descripcion = "No tan cool" }
    };
    
    
    //Para simular un ID auto_incrementable:
    private int contador = _productos.Count();
    
    
    // Traigo la lista:
    public IActionResult Index()
    {
        return View(_productos);
    }


    // Para mostrar los detalles de los productos:
    public IActionResult Details(int id)
    {
        var produc = _productos;

        var pro = produc.FirstOrDefault(produc => produc.ID == id);
        if (pro == null) 
            return NotFound();
        return View(pro);
    }
    
    
    
    // CREATE:
    public IActionResult Store(Producto producto)
    {
        contador++;
        producto.ID = contador;
        _productos.Add(producto);
        return RedirectToAction("Index");
    }


    // DELETE:
    public IActionResult Deleting(int id_prod)
    {
        var pro = _productos.FirstOrDefault(produc => produc.ID == id_prod);
        if (pro != null)
        {
            _productos.Remove(pro);
        }
        
        return RedirectToAction("Index");
    }
    

    // EDITAR:  
    // GET: Producto/Edit/1
    public IActionResult Edit(int id)
    {
        var producto = _productos.FirstOrDefault(p => p.ID == id);
        if (producto == null)
        {
            return NotFound();
        }
        return View(producto);
    }

    [HttpPost]
    public IActionResult EditPost(Producto producto)
    {
        var existingProduct = _productos.FirstOrDefault(p => p.ID == producto.ID);
        if (existingProduct == null)
        {
            return NotFound();
        }

        // Actualizar propiedades
        existingProduct.Nombre = producto.Nombre;
        existingProduct.Descripcion = producto.Descripcion;
        existingProduct.Precio = producto.Precio;

        return RedirectToAction("Index");
    }

}

Views/Cliente/EditCliente.cshtml
@model inicio_Mvc_Csharp.Models.Cliente

<h2>Editar Cliente</h2>

<form asp-action="EditPost" method="post">
    <input type="hidden" asp-for="Id" />
    
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Cedula"></label>
        <input asp-for="Cedula" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Edad"></label>
        <input asp-for="Edad" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary mt-3">Guardar cambios</button>
    <a asp-action="Index" class="btn btn-secondary mt-3">Cancelar</a>
</form>

Views/Cliente/Index.cshtml
@model IEnumerable<inicio_Mvc_Csharp.Models.Cliente>

<h1>Lista de clientes</h1>

<div class="row">
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <form asp-action="Store">
                    <h5>Crear un nuevo cliente</h5>
                    <div class="mt-3 d-flex flex-column">
                        <label for="nombre_c">Nombre</label>
                        <input id="nombre_c" type="text" class="form-control" name="nombre_c" required autofocus>
                    </div>

                    <div class="mt-3 d-flex flex-column">
                        <label for="cedula">Cédula</label>
                        <input id="cedula" type="number" class="form-control" name="cedula" placeholder="1010101010" required>
                    </div>
                    @* TODO *@
                    <div class="mt-3 d-flex flex-column">
                        <label for="producto">Producto</label>
                        <select id="producto" class="form-control" name="ProductoId" required>
                            <option value="">-- Selecciona un producto --</option>
                            @foreach (var p in ViewBag.Productos as List<inicio_Mvc_Csharp.Models.Producto>)
                            {
                                <option value="@p.ID">@p.Nombre</option>
                            }
                        </select>
                    </div>
                    <hr>
                    <button type="submit" class="btn btn-success w-100">Guardar</button>
                </form>
            </div>
        </div>
    </div>
    
    <div class="col-md-9">
        <table class="table table-striped">
            <!--Encabezados-->
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Nombre</td>
                    <td>Cédula</td>
                    <td>Edad</td>
                    <td>Producto</td>
                    <td>Acciones</td>
                </tr>
            </thead>
    
            <!--Cuerpo de la tabla-->
            <tbody>
            @foreach (var c in Model)
            {
                <tr>
                    <td>@c.Id</td>
                    <td>@c.Nombre</td>
                    <td>@c.Cedula</td>
                    <td>@c.Edad</td>
                    <td>@c.Producto?.Nombre</td>
                    <td>
                        @* <a class="btn btn-primary" asp-action="Details" asp-controller="Producto" asp-route-id="@c.Id">Detalles</a> *@
                        <a class="btn btn-warning" asp-action="EditCliente" asp-controller="Cliente" asp-route-id="@c.Id">Editar</a>
                        <a class="btn btn-danger" asp-action="DeleteCliente" onclick="return confirm('¿Quiere eliminar este cliente?');" asp-controller="Cliente" asp-route-id_cliente="@c.Id" >Delete</a>
                    </td>
                </tr>
            }
            </tbody>
    
        </table>
    </div>
</div>

Views/Hello/Index.cshtml
<h1> Hola mundo </h1>

<p>Soy Diego.</p>
<p>Estoy en Riwi en C#</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Producto/Details.cshtml
@model inicio_Mvc_Csharp.Models.Producto

<h1>Funciona</h1>

<table class="table">
    <thead>
        <tr>
            <td>ID</td>
            <td>Nombre</td>
            <td>Precio</td>
            <td>Descripcion</td>
        </tr>
    </thead>
    
    <tbody>
        <td>@Model.ID</td>
        <td>@Model.Nombre</td>
        <td>@Model.Precio</td>
        <td>@Model.Descripcion</td>
        <td>
            <a class="btn btn-primary" asp-action="Index" asp-controller="Producto">Volver</a>
        </td>
    </tbody>
</table>

Views/Producto/Edit.cshtml
@model inicio_Mvc_Csharp.Models.Producto

<h2>Editar Producto</h2>

<form asp-action="EditPost" method="post">
    <input type="hidden" asp-for="ID" />
    
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Descripcion"></label>
        <input asp-for="Descripcion" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Precio"></label>
        <input asp-for="Precio" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary mt-3">Guardar cambios</button>
    <a asp-action="Index" class="btn btn-secondary mt-3">Cancelar</a>
</form>

Views/Producto/Index.cshtml
@model IEnumerable<inicio_Mvc_Csharp.Models.Producto>

<h1>Lista de productos</h1>


<div class="row">
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <form asp-action="Store">
                    <h5>Crear un nuevo producto</h5>
                    <div class="mt-3 d-flex flex-column">
                        <label for="nombre_p">Nombre</label>
                        <input id="nombre_p" type="text" class="form-control" name="nombre_p" required >
                    </div>

                    <div class="mt-3 d-flex flex-column">
                        <label for="descripcion">Descripcion</label>
                        <input id="descripcion" type="text" class="form-control" name="Descripcion" placeholder="Descripcion del producto" required>
                    </div>

                    <div class="mt-3 d-flex flex-column">
                        <label for="precio">Precio</label>
                        <input id="precio" type="number" class="form-control" name="precio" required>
                    </div>
                    <hr>
                    <button type="submit" class="btn btn-success w-100">Guardar información</button>
                </form>
            </div>
        </div>
    </div>    
    
    
    <div class="col-md-9">
        
        <table class="table table-striped">
            <!--Encabezados-->
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Nombre</td>
                    <td>Precio</td>
                    <td>Descripción</td>
                    <td>Acciones</td>
                </tr>
            </thead>
    
            <!--Cuerpo de la tabla-->
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.ID</td>
                    <td>@item.Nombre</td>
                    <td>@item.Precio</td>
                    <td>@item.Descripcion</td>
                    <td>
                        <a class="btn btn-primary" asp-action="Details" asp-controller="Producto" asp-route-id="@item.ID">Detalles</a>
                        <a class="btn btn-warning" asp-action="Edit" asp-controller="Producto" asp-route-id="@item.ID">Editar</a>
                        <a class="btn btn-danger" asp-action="Deleting" onclick="return confirm('¿Do you want to delete this product?');" asp-controller="Producto" asp-route-id_prod="@item.ID" >Delete</a>
                    </td>
                </tr>
            }
            </tbody>
    
        </table>
    </div>
    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - inicio_Mvc_Csharp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/inicio_Mvc_Csharp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mi Primer E-commerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Diego Vallejo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>